**Consider the below code to answer further questions:**

```python
import numpy as np
list_ = [ '1', '2', '3', '4', '5' ]
array_list = np.array(object = list_)
```

**Q1.** Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

**Answer:**

Yes, there is a difference in the data type of the `list_` variable and the `array_list` variable. 

The `list_` variable is a Python list, which can hold elements of different data types. In this case, it contains strings.

The `array_list` variable is a NumPy array, which is a homogeneous data structure that can only hold elements of a single data type. In this case, it contains strings as well, but they will be stored as NumPy string data type.

To print the data types of both variables, you can use the `type()` function in Python:

```python
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
```

When you run this code, it will output:

```
Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>
```

This confirms that `list_` is of type `list` and `array_list` is of type `numpy.ndarray`.

**Q2.** Write a code to print the data type of each and every element of both the variables list_ and array_list.

**Answer:**


In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Q3.** Considering the following changes in the variable, array_list:
```python
array_list = np.array(object = list_, dtype = int)
```
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

**Answer:**

Yes, there will be a difference in the data type of the elements present in `list_` and `array_list` after the change.

When creating `array_list` with the modified code `np.array(object = list_, dtype = int)`, the `dtype` parameter is set to `int`. This means that the elements in `array_list` will be converted to `integers`.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


**Consider the below code to answer further questions:**
```python
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```

**Q4.** Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

**Answer:**


In [9]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print("Shape of num_array: ", num_array.shape)
print("Size of num_array: ", num_array.size)

Shape of num_array:  (2, 3)
Size of num_array:  6


**Q5.** Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

**Answer:**


In [11]:
import numpy as np

mat = np.zeros((3, 3))

print(mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Q6.** Create an identity matrix of shape (5,5) using numpy functions?

**Answer:**


In [14]:
import numpy as np

identity_mat = np.eye((5))

print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
